language: python
os: linux
env:
 - DIST=trusty

python:
   - "2.7"
   - "3.5"

cache:
   - pip

addons:
   apt:
      packages:
         - libhdf5-serial-dev
         - netcdf-bin
         - libnetcdf-dev

before_install:
   - "export DISPLAY=:99.0"
   - "export MPLCONFIGDIR=/tmp/"
   - "sh -e /etc/init.d/xvfb start"
   - sudo apt-get -qq update
   - sudo apt-get install -y python-numpy python-scipy python-matplotlib python-mpltoolkits.basemap

install:
   - pip install .

script:
   - pip install coveralls pep8
   - wxgen
   - nosetests -v --with-coverage --cover-erase --cover-package=wxgen

after_success:
   - coveralls
